repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint --rcfile=.pylintrc linx
        language: system
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest linx
        language: system
        pass_filenames: false
