name: graphica_dev_env
channels:
  - conda-forge
  - defaults
  - edderic
dependencies:
  - conda-build
  - dask
  - jupyter
  - jupyterlab
  - line_profiler
  - matplotlib
  - numpy
  - pandas
  - pyarrow
  - pre-commit
  - pylint
  - python
  - python-graphviz
  - pytest
  - seaborn
  - scikit-learn
  - tqdm
