{% set name = "linx" %}
{% set version = "0.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python {{ python }}
  host:
    - pip
    - python {{ python }}
  run:
    - matplotlib
    - numpy
    - pandas
    - python
    - tqdm

about:
  home: "https://github.com/edderic/linx"
  license: MIT
  license_family: MIT
  summary: "Tools for Probabilistic Graphical Modeling"
  dev_url: "https://github.com/edderic/linx"

extra:
  recipe-maintainers:
    - edderic
test:
  imports:
    - linx
    - linx.ds
    - linx.query
    - linx.bayesian_network
    - linx.markov_network
    - linx.infer
    - linx.conditional_probability_table
    - linx.factor
    - linx.variable_elimination

