{% set name = "graphica" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python {{ python }}
  host:
    - pip
    - python {{ python }}
  run:
    - matplotlib
    - numpy
    - pandas
    - python
    - tqdm

about:
  home: "https://github.com/edderic/graphica"
  license: MIT
  license_family: MIT
  summary: "Tools for Probabilistic Graphical Modeling"
  dev_url: "https://github.com/edderic/graphica"

extra:
  recipe-maintainers:
    - edderic
test:
  imports:
    - graphica
    - graphica.ds
    - graphica.query
    - graphica.bayesian_network
    - graphica.markov_network
    - graphica.infer
    - graphica.conditional_probability_table
    - graphica.factor
    - graphica.variable_elimination

